repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: \.py$
      - id: black-jupyter
        files: \.ipynb$
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--ignore=E501,W503,E203']
        files: \.py$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: greengrass/components/(frontend_cms|frontend_cmsrgb)/src/
        types_or: [ts, tsx, javascript, css]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
     -  id: mypy
        args: [--follow-imports=skip, --show-error-codes]
        additional_dependencies: ['types-requests', 'types-pyyaml']
        files: src/rtcode/
